language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script:
  - bash -ex .travis-docker.sh
  - bash .travis-python-nosetests.sh
env:
  global:
    - PACKAGE="xapi-xenopsd"
    - PINS="xapi-xenopsd:. xapi-xenopsd-xc:. xapi-xenopsd-simulator:."
    - BASE_REMOTE="https://github.com/xapi-project/xs-opam.git"
    - OCAML_VERSION="4.07"
    - DISTRO="debian-unstable"
  matrix:
    - PACKAGE="xapi-xenopsd"
    - PACKAGE="xapi-xenopsd-xc"
    - PACKAGE="xapi-xenopsd-simulator"
